version: "3.9"

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MY_CHAT_ID=${MY_CHAT_ID}
      - KEYWORDS=${KEYWORDS}
    volumes:
      - ./logs:/app/logs       # 🔹 monta a pasta de logs do host no container
    tty: true
